### PR TITLE
 Updated version of glob and mocha for audit

### PR DESCRIPTION
**Pull request by bergur**
glob v4 is using an old version of minmatch which has the following vulnerbility
https://nodesecurity.io/advisories/118

I updated glob version to 7 to fix this problem.

I also updated mocha version so that when running npm audit mocha-only-detector has no kown vulnerabilities.

### CODE REVIEW

**Comment by bergur** [comment]
Any news on this? glob4 is really outdated and it would be nice to have the latest version of it.

**Comment by Tehem** [comment]
I was about to propose the same update, please merge the version bump! Thanks.

**Comment by pose** [comment]
Sorry for the delay @Tehem @bergur. I've cherry picked your commit and updated the package version of `esprima` as well. `1.0.1` has been released. Thanks.

**Comment by bergur** [comment]
No worries, thanks for your time and effort :)

**Pull request closed without merging**
